name: urbanlanegraph
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - appdirs=1.4.4
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.3
  - cloudpickle=2.2.1
  - cryptography=39.0.1
  - cudatoolkit=11.3.1
  - cytoolz=0.12.0
  - dask-core=2023.4.0
  - docker-pycreds=0.4.0
  - enum34=1.1.10
  - ffmpeg=4.3
  - flit-core=3.8.0
  - freetype=2.12.1
  - fsspec=2023.4.0
  - giflib=5.2.1
  - gitdb=4.0.10
  - gitpython=3.1.31
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.4
  - imagecodecs-lite=2019.12.3
  - imageio=2.27.0
  - importlib-metadata=6.5.0
  - importlib_metadata=6.5.0
  - intel-openmp=2021.4.0
  - jinja2=3.1.2
  - joblib=1.1.1
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuv=1.44.2
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - locket=1.0.0
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openh264=2.1.1
  - openssl=1.1.1t
  - packaging=23.0
  - partd=1.4.0
  - pathlib=1.0.1
  - pathtools=0.1.2
  - pillow=9.4.0
  - pip=23.0.1
  - pooch=1.4.0
  - protobuf=3.20.3
  - psutil=5.9.0
  - pycparser=2.21
  - pyg=2.1.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.8.16
  - python_abi=3.8
  - pytorch=1.11.0
  - pytorch-cluster=1.6.0
  - pytorch-mutex=1.0
  - pytorch-scatter=2.0.9
  - pytorch-sparse=0.6.15
  - pywavelets=1.4.1
  - pyyaml=6.0
  - readline=8.2
  - requests=2.28.1
  - scikit-image=0.19.2
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - sentry-sdk=1.19.1
  - setproctitle=1.1.10
  - setuptools=66.0.0
  - six=1.16.0
  - smmap=3.0.5
  - sqlite=3.41.2
  - threadpoolctl=2.2.0
  - tifffile=2019.7.26.2
  - tk=8.6.12
  - toolz=0.12.0
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - tqdm=4.65.0
  - typing_extensions=4.4.0
  - urllib3=1.26.15
  - wandb=0.14.2
  - wheel=0.38.4
  - xz=5.2.10
  - yaml=0.2.5
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - affine==2.4.0
      - aiohttp==3.8.4
      - aiohttp-cors==0.7.0
      - aiosignal==1.3.1
      - async-timeout==4.0.2
      - attrs==23.1.0
      - blessed==1.20.0
      - cachetools==5.3.0
      - click-plugins==1.1.1
      - cligj==0.7.2
      - colorful==0.5.5
      - contourpy==1.0.7
      - cssselect2==0.7.0
      - cycler==0.11.0
      - fiona==1.9.3
      - fonttools==4.39.3
      - frozenlist==1.3.3
      - geopandas==0.12.2
      - google-api-core==2.11.0
      - google-auth==2.17.3
      - googleapis-common-protos==1.59.0
      - gpustat==1.1
      - grpcio==1.54.0
      - importlib-resources==5.12.0
      - jsonschema==4.17.3
      - kiwisolver==1.4.4
      - lxml==4.9.2
      - matplotlib==3.7.1
      - msgpack==1.0.5
      - multidict==6.0.4
      - munch==2.5.0
      - nvidia-ml-py==11.525.112
      - opencensus==0.11.2
      - opencensus-context==0.1.3
      - opencv-python==4.7.0.72
      - osmnx==1.2.2
      - pandas==2.0.0
      - pkgutil-resolve-name==1.3.10
      - prometheus-client==0.16.0
      - py-spy==0.3.14
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pydantic==1.10.7
      - pyproj==3.5.0
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - pytz==2023.3
      - rasterio==1.3.6
      - ray==2.3.1
      - reportlab==3.6.12
      - rsa==4.9
      - rtree==1.0.1
      - scikit-fmm==2023.4.2
      - shapely==1.8.5.post1
      - smart-open==6.3.0
      - snuggs==1.4.7
      - svglib==1.5.1
      - tinycss2==1.2.1
      - tzdata==2023.3
      - utm==0.7.0
      - wcwidth==0.2.6
      - webencodings==0.5.1
      - yarl==1.8.2

